-- DOC (Doctor On Call) database schema for Supabase Postgres. Generated by scripts/make_schema.py.
-- Security model: the browser never talks to Supabase. Only the DOC API connects (service role / table owner).
-- Row-level security is ENABLED with NO policies on every table = deny-all for anon/authenticated roles.
-- All authorization (owner checks, family consent, permission filtering) is enforced in backend code.

create extension if not exists vector;

CREATE TABLE contact_messages (
	id SERIAL NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	topic VARCHAR(40) NOT NULL, 
	message TEXT NOT NULL, 
	ip VARCHAR(64), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);

CREATE TABLE users (
	id SERIAL NOT NULL, 
	email VARCHAR(255) NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	password_hash VARCHAR(255) NOT NULL, 
	language VARCHAR(8) NOT NULL, 
	totp_secret_enc TEXT, 
	totp_enabled BOOLEAN NOT NULL, 
	backup_codes JSON NOT NULL, 
	firebase_uid VARCHAR(128), 
	auth_provider VARCHAR(40), 
	email_verified BOOLEAN NOT NULL, 
	is_demo BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id)
);
CREATE UNIQUE INDEX ix_users_email ON users (email);
CREATE UNIQUE INDEX ix_users_firebase_uid ON users (firebase_uid);

CREATE TABLE audit_logs (
	id SERIAL NOT NULL, 
	user_id INTEGER, 
	subject_user_id INTEGER, 
	action VARCHAR(60) NOT NULL, 
	detail TEXT, 
	ip VARCHAR(64), 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_audit_logs_subject_user_id ON audit_logs (subject_user_id);
CREATE INDEX ix_audit_logs_user_id ON audit_logs (user_id);

CREATE TABLE profiles (
	id SERIAL NOT NULL, 
	user_id INTEGER NOT NULL, 
	name VARCHAR(120) NOT NULL, 
	relation VARCHAR(40) NOT NULL, 
	sex VARCHAR(1) NOT NULL, 
	dob DATE, 
	height_cm FLOAT, 
	weight_kg FLOAT, 
	conditions JSON NOT NULL, 
	is_primary BOOLEAN NOT NULL, 
	color VARCHAR(16) NOT NULL, 
	blood_group VARCHAR(4), 
	allergies JSON NOT NULL, 
	emergency_name VARCHAR(120), 
	emergency_phone VARCHAR(20), 
	abha_number VARCHAR(17), 
	abha_address VARCHAR(80), 
	abha_linked_at TIMESTAMP WITH TIME ZONE, 
	profile_incomplete BOOLEAN NOT NULL, 
	rag_signature VARCHAR(64), 
	is_demo BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES users (id) ON DELETE CASCADE
);
CREATE INDEX ix_profiles_user_id ON profiles (user_id);

CREATE TABLE checkups (
	id SERIAL NOT NULL, 
	profile_id INTEGER NOT NULL, 
	title VARCHAR(160) NOT NULL, 
	kind VARCHAR(20) NOT NULL, 
	due_date DATE, 
	done_date DATE, 
	repeat_months INTEGER, 
	provider VARCHAR(160), 
	notes TEXT, 
	is_demo BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
CREATE INDEX ix_checkups_profile_id ON checkups (profile_id);

CREATE TABLE chunks (
	id SERIAL NOT NULL, 
	profile_id INTEGER NOT NULL, 
	source_type VARCHAR(20) NOT NULL, 
	source_id VARCHAR(40) NOT NULL, 
	section VARCHAR(20) NOT NULL, 
	text TEXT NOT NULL, 
	embedding VECTOR(1024) NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
CREATE INDEX ix_chunks_profile_id ON chunks (profile_id);

CREATE TABLE devices (
	id SERIAL NOT NULL, 
	profile_id INTEGER NOT NULL, 
	kind VARCHAR(30) NOT NULL, 
	name VARCHAR(80) NOT NULL, 
	connected_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	last_sync_at TIMESTAMP WITH TIME ZONE, 
	is_demo BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
CREATE INDEX ix_devices_profile_id ON devices (profile_id);

CREATE TABLE family_links (
	id SERIAL NOT NULL, 
	requester_id INTEGER NOT NULL, 
	owner_id INTEGER, 
	owner_email VARCHAR(255) NOT NULL, 
	owner_profile_id INTEGER, 
	relation VARCHAR(40) NOT NULL, 
	message VARCHAR(300), 
	status VARCHAR(12) NOT NULL, 
	requested_permissions JSON NOT NULL, 
	permissions JSON NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	responded_at TIMESTAMP WITH TIME ZONE, 
	revoked_at TIMESTAMP WITH TIME ZONE, 
	is_demo BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(requester_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(owner_id) REFERENCES users (id) ON DELETE CASCADE, 
	FOREIGN KEY(owner_profile_id) REFERENCES profiles (id) ON DELETE SET NULL
);
CREATE INDEX ix_family_links_owner_email ON family_links (owner_email);
CREATE INDEX ix_family_links_owner_id ON family_links (owner_id);
CREATE INDEX ix_family_links_requester_id ON family_links (requester_id);
CREATE INDEX ix_family_links_status ON family_links (status);

CREATE TABLE meal_logs (
	id SERIAL NOT NULL, 
	profile_id INTEGER NOT NULL, 
	eaten_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	meal_type VARCHAR(12) NOT NULL, 
	items JSON NOT NULL, 
	totals JSON NOT NULL, 
	source VARCHAR(12) NOT NULL, 
	note VARCHAR(300), 
	is_demo BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
CREATE INDEX ix_meal_logs_eaten_at ON meal_logs (eaten_at);
CREATE INDEX ix_meal_logs_profile_id ON meal_logs (profile_id);

CREATE TABLE reports (
	id SERIAL NOT NULL, 
	profile_id INTEGER NOT NULL, 
	filename VARCHAR(255) NOT NULL, 
	stored_name VARCHAR(255), 
	mime VARCHAR(80), 
	kind VARCHAR(20) NOT NULL, 
	lab_name VARCHAR(160), 
	doctor_name VARCHAR(160), 
	report_date DATE, 
	status VARCHAR(20) NOT NULL, 
	method VARCHAR(20) NOT NULL, 
	notes TEXT, 
	pages INTEGER, 
	ocr_text TEXT, 
	user_verified BOOLEAN NOT NULL, 
	is_demo BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
CREATE INDEX ix_reports_profile_id ON reports (profile_id);

CREATE TABLE share_links (
	id SERIAL NOT NULL, 
	profile_id INTEGER NOT NULL, 
	token VARCHAR(64) NOT NULL, 
	expires_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	revoked BOOLEAN NOT NULL, 
	views INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
CREATE INDEX ix_share_links_profile_id ON share_links (profile_id);
CREATE UNIQUE INDEX ix_share_links_token ON share_links (token);

CREATE TABLE symptoms (
	id SERIAL NOT NULL, 
	profile_id INTEGER NOT NULL, 
	key VARCHAR(40) NOT NULL, 
	label VARCHAR(120) NOT NULL, 
	onset_date DATE NOT NULL, 
	severity INTEGER NOT NULL, 
	notes TEXT, 
	PRIMARY KEY (id), 
	FOREIGN KEY(profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
CREATE INDEX ix_symptoms_profile_id ON symptoms (profile_id);

CREATE TABLE vital_readings (
	id SERIAL NOT NULL, 
	profile_id INTEGER NOT NULL, 
	kind VARCHAR(20) NOT NULL, 
	value FLOAT NOT NULL, 
	value2 FLOAT, 
	context VARCHAR(20), 
	measured_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	source VARCHAR(20) NOT NULL, 
	note TEXT, 
	is_demo BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
CREATE INDEX ix_vital_readings_kind ON vital_readings (kind);
CREATE INDEX ix_vital_readings_measured_at ON vital_readings (measured_at);
CREATE INDEX ix_vital_readings_profile_id ON vital_readings (profile_id);

CREATE TABLE wound_scans (
	id SERIAL NOT NULL, 
	profile_id INTEGER NOT NULL, 
	label VARCHAR(80) NOT NULL, 
	stored_name VARCHAR(300), 
	mime VARCHAR(40), 
	metrics JSON NOT NULL, 
	answers JSON NOT NULL, 
	result JSON NOT NULL, 
	is_demo BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
CREATE INDEX ix_wound_scans_created_at ON wound_scans (created_at);
CREATE INDEX ix_wound_scans_profile_id ON wound_scans (profile_id);

CREATE TABLE lab_results (
	id SERIAL NOT NULL, 
	report_id INTEGER NOT NULL, 
	profile_id INTEGER NOT NULL, 
	test_code VARCHAR(32), 
	test_name_raw VARCHAR(160) NOT NULL, 
	value FLOAT, 
	unit VARCHAR(32), 
	value_raw VARCHAR(40), 
	unit_raw VARCHAR(40), 
	ref_low FLOAT, 
	ref_high FLOAT, 
	flag VARCHAR(2), 
	date DATE, 
	confidence FLOAT NOT NULL, 
	source_text TEXT, 
	page INTEGER, 
	confirmed BOOLEAN NOT NULL, 
	user_verified BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(report_id) REFERENCES reports (id) ON DELETE CASCADE, 
	FOREIGN KEY(profile_id) REFERENCES profiles (id) ON DELETE CASCADE
);
CREATE INDEX ix_lab_results_profile_id ON lab_results (profile_id);
CREATE INDEX ix_lab_results_report_id ON lab_results (report_id);
CREATE INDEX ix_lab_results_test_code ON lab_results (test_code);

CREATE TABLE medications (
	id SERIAL NOT NULL, 
	profile_id INTEGER NOT NULL, 
	report_id INTEGER, 
	brand VARCHAR(120) NOT NULL, 
	generic VARCHAR(160), 
	drug_class VARCHAR(80), 
	dose VARCHAR(60), 
	frequency VARCHAR(60), 
	start_date DATE, 
	end_date DATE, 
	active BOOLEAN NOT NULL, 
	reason VARCHAR(160), 
	confidence FLOAT NOT NULL, 
	source_text TEXT, 
	is_demo BOOLEAN NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(profile_id) REFERENCES profiles (id) ON DELETE CASCADE, 
	FOREIGN KEY(report_id) REFERENCES reports (id) ON DELETE SET NULL
);
CREATE INDEX ix_medications_profile_id ON medications (profile_id);

CREATE TABLE reminders (
	id SERIAL NOT NULL, 
	profile_id INTEGER NOT NULL, 
	kind VARCHAR(20) NOT NULL, 
	title VARCHAR(160) NOT NULL, 
	detail VARCHAR(300), 
	times JSON NOT NULL, 
	days JSON NOT NULL, 
	start_date DATE, 
	end_date DATE, 
	active BOOLEAN NOT NULL, 
	medication_id INTEGER, 
	done_log JSON NOT NULL, 
	is_demo BOOLEAN NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE NOT NULL, 
	PRIMARY KEY (id), 
	FOREIGN KEY(profile_id) REFERENCES profiles (id) ON DELETE CASCADE, 
	FOREIGN KEY(medication_id) REFERENCES medications (id) ON DELETE SET NULL
);
CREATE INDEX ix_reminders_profile_id ON reminders (profile_id);

-- Vector search (cosine) over a person's own chunks
create index if not exists chunks_embedding_hnsw on chunks using hnsw (embedding vector_cosine_ops);
create or replace function match_chunks(query_embedding vector(1024), p_profile_id integer, match_count integer default 6)
returns table (id integer, source_type varchar, source_id varchar, text text, similarity double precision)
language sql stable as $$
  select c.id, c.source_type, c.source_id, c.text, 1 - (c.embedding <=> query_embedding) as similarity
  from chunks c
  where c.profile_id = p_profile_id
  order by c.embedding <=> query_embedding
  limit match_count;
$$;

-- Deny-all RLS
alter table "contact_messages" enable row level security;
alter table "users" enable row level security;
alter table "audit_logs" enable row level security;
alter table "profiles" enable row level security;
alter table "checkups" enable row level security;
alter table "chunks" enable row level security;
alter table "devices" enable row level security;
alter table "family_links" enable row level security;
alter table "meal_logs" enable row level security;
alter table "reports" enable row level security;
alter table "share_links" enable row level security;
alter table "symptoms" enable row level security;
alter table "vital_readings" enable row level security;
alter table "wound_scans" enable row level security;
alter table "lab_results" enable row level security;
alter table "medications" enable row level security;
alter table "reminders" enable row level security;

-- Private storage bucket for encrypted files (the API also creates it on start-up)
insert into storage.buckets (id, name, public) values ('health-files', 'health-files', false) on conflict (id) do nothing;
