"""Write backend/schema.sql (Postgres / Supabase) from the SQLAlchemy models.

The API also applies all of this automatically on start-up (init_db), so running the file by hand in the
Supabase SQL editor is optional. Usage:  python -m scripts.make_schema   (from backend/)
"""
from pathlib import Path

from sqlalchemy.dialects import postgresql
from sqlalchemy.schema import CreateIndex, CreateTable

from app import models  # noqa: F401  (register tables)
from app.database import MATCH_CHUNKS_SQL, Base

OUT = Path(__file__).resolve().parents[1] / "schema.sql"


def main():
    dialect = postgresql.dialect()
    parts = ["-- DOC (Doctor On Call) database schema for Supabase Postgres. Generated by scripts/make_schema.py.",
             "-- Security model: the browser never talks to Supabase. Only the DOC API connects (service role / table owner).",
             "-- Row-level security is ENABLED with NO policies on every table = deny-all for anon/authenticated roles.",
             "-- All authorization (owner checks, family consent, permission filtering) is enforced in backend code.", "",
             "create extension if not exists vector;", ""]
    for table in Base.metadata.sorted_tables:
        parts.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";")
        for idx in sorted(table.indexes, key=lambda i: i.name or ""):
            parts.append(str(CreateIndex(idx).compile(dialect=dialect)).strip() + ";")
        parts.append("")
    parts.append("-- Vector search (cosine) over a person's own chunks")
    parts.append("create index if not exists chunks_embedding_hnsw on chunks using hnsw (embedding vector_cosine_ops);")
    parts.append(MATCH_CHUNKS_SQL.strip())
    parts.append("")
    parts.append("-- Deny-all RLS")
    for table in Base.metadata.sorted_tables:
        parts.append(f'alter table "{table.name}" enable row level security;')
    parts.append("")
    parts.append("-- Private storage bucket for encrypted files (the API also creates it on start-up)")
    parts.append("insert into storage.buckets (id, name, public) values ('health-files', 'health-files', false) on conflict (id) do nothing;")
    OUT.write_text("\n".join(parts) + "\n", encoding="utf-8")
    print(f"wrote {OUT} ({len(Base.metadata.sorted_tables)} tables)")


if __name__ == "__main__":
    main()
